sudo: true
dist: trusty

env:
  matrix:
    - CI_NODE=1 RSPEC=1 RSPEC_PATTERN="spec/{controllers,helpers,lib,mailers,models}/**/*.rb"
    - CI_NODE=2 RSPEC=1 RSPEC_PATTERN="spec/{features,usermanual}/**/*.rb"
    - CI_NODE=3 RSPEC=1 RSPEC_PATTERN="spec/integration/{running_tests,comet,feedback,requests}/**/*.rb"
    - CI_NODE=4 RSPEC=1 RSPEC_PATTERN="spec/integration/*.rb"
    - CI_NODE=5 BREAKMAN=1
    - CI_NODE=6 AUDIT=1
  global:
    - secure: XC/0F2K3EyGYrOtS9G+YddR9iW0E/eUBCe7dyjIHT3bAuWmkNLbGaWFvRaRALGCLJaQBzksEwQE47+qv4nS72kuVElHws5S3YU7PYT3A4KENe4pdycx9YitLj1eh7F4ds4LUEJ2TmjRw1+fvlsAXJ//ZW/vqzAxeZPrJPOF52tY=

language: ruby
rvm:
  - 2.2.0

git:
  submodules: false

addons:
  apt:
    packages:
      - valgrind
      - check
      - pkg-config
      - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine
  - . ./setup-travis.sh

install:
  - bundle install --retry=3 --jobs=3 --deployment
  - docker pull jamo/tmc-sandbox
  - mkdir devshm

services:
  - docker
  - postgresql

before_script:
  - createuser -U postgres -s tmc
  - bundle exec rake db:reset

script:
  - docker run -t --privileged --network="host" -p 3001:3001  -v devshm:/dev/shm jamo/tmc-sandbox /bin/sh -c "cd tmc-sandbox/uml/ && ./run-test-exercise.sh && tar xvf tmp/output.tar && find tmp/*.txt -print -exec cat {} \;"
  - if [ ! -z "$RSPEC" ]; then docker run -d --privileged --network="host" -p 3001:3001  -v devshm:/dev/shm jamo/tmc-sandbox ; fi
  - if [ ! -z "$RSPEC" ]; then curl 127.0.0.1:3001/status.json ; fi
  - if [ ! -z "$RSPEC" ]; then bundle exec rake spec SPEC_OPTS="--pattern $RSPEC_PATTERN --tag ~network -f d" SANDBOX_HOST=127.0.0.1 SANDBOX_PORT=3001; fi
  - if [ ! -z "$BREAKMAN" ]; then bundle --binstubs && ./bin/brakeman ; fi
  - if [ ! -z "$AUDIT" ]; then bundle exec bundle-audit update && bundle exec bundle-audit check ; fi

after_success:
  - ./.travis-update-usermanual.sh

after_failure:
  - cat ext/tmc-sandbox/web/log/*

notifications:
  slack:
    secure: YCiWybZYBoJ2JDjpPp5Idf4OvqScay5WfEuQMdvee42kgsSVolew6V5YUx41E29Of+2xAcQ+be5XImzO7SlTYuaGD6hf0JZvjjxO3gpycCljNSvDgFnBF9s4WuUQ31LozI6eQqo/9c5zUFxW9MGeeaRUWvurlW0rRHM3UKokAQk=
