version: '2'
services:
  sandbox:
    image: testmycode/tmc-sandbox:0.0.3
    expose:
      - 3001
    volumes:
      - /tmp:/dev/shm
  db:
    image: postgres:9.4
  dev:
    build: .
    command: rails s -b 0.0.0.0 --pid=/tmp/dev.pid
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - HOST=dev
      - SANDBOX_URL=http://sandbox:3001
    depends_on:
      - db
      - sandbox
